// Demo data for local development without Supabase connection
// This allows the app to work standalone with realistic data

import type {
  Debt,
  NetWorthSnapshot,
  BudgetCategory,
  Expense,
  Contact,
  LegalDocument,
  FinancialAccount,
  InsurancePolicy,
  MonthlyBill,
  DigitalAccess,
  ActionItem,
} from "./types";

const DEMO_USER_ID = "demo-user";

export const demoDebts: Debt[] = [
  {
    id: "d1",
    user_id: DEMO_USER_ID,
    card_name: "Chase Sapphire Reserve",
    balance: 5200,
    apr: 24.99,
    min_payment: 130,
    is_paid_off: false,
    paid_off_date: null,
    created_at: "2026-01-01",
  },
  {
    id: "d2",
    user_id: DEMO_USER_ID,
    card_name: "Citi Double Cash",
    balance: 4100,
    apr: 19.99,
    min_payment: 102,
    is_paid_off: false,
    paid_off_date: null,
    created_at: "2026-01-01",
  },
  {
    id: "d3",
    user_id: DEMO_USER_ID,
    card_name: "Capital One Venture",
    balance: 3400,
    apr: 17.49,
    min_payment: 85,
    is_paid_off: false,
    paid_off_date: null,
    created_at: "2026-01-01",
  },
  {
    id: "d4",
    user_id: DEMO_USER_ID,
    card_name: "Amazon Prime Visa",
    balance: 2300,
    apr: 15.24,
    min_payment: 58,
    is_paid_off: false,
    paid_off_date: null,
    created_at: "2026-01-01",
  },
];

export const demoNetWorthSnapshots: NetWorthSnapshot[] = [
  {
    id: "nw1",
    user_id: DEMO_USER_ID,
    snapshot_date: "2025-10-01",
    assets: {
      cash: { emergency_fund: 8000, checking: 10000 },
      retirement: { tesla_401k: 22000, roth_ira_his: 14000, roth_ira_hers: 11000 },
      investments: { schwab_brokerage: 5500, thinkorswim: 3200 },
      education: {},
      other: { crypto: 1800 },
    },
    liabilities: { credit_cards: { total: 18000 }, loans: {} },
    total_assets: 75500,
    total_liabilities: 18000,
    net_worth: 57500,
    created_at: "2025-10-01",
  },
  {
    id: "nw2",
    user_id: DEMO_USER_ID,
    snapshot_date: "2025-11-01",
    assets: {
      cash: { emergency_fund: 8500, checking: 11000 },
      retirement: { tesla_401k: 22500, roth_ira_his: 14800, roth_ira_hers: 11500 },
      investments: { schwab_brokerage: 5800, thinkorswim: 3400 },
      education: {},
      other: { crypto: 1900 },
    },
    liabilities: { credit_cards: { total: 17200 }, loans: {} },
    total_assets: 79400,
    total_liabilities: 17200,
    net_worth: 62200,
    created_at: "2025-11-01",
  },
  {
    id: "nw3",
    user_id: DEMO_USER_ID,
    snapshot_date: "2025-12-01",
    assets: {
      cash: { emergency_fund: 9000, checking: 11500 },
      retirement: { tesla_401k: 23000, roth_ira_his: 15200, roth_ira_hers: 12000 },
      investments: { schwab_brokerage: 6100, thinkorswim: 3600 },
      education: {},
      other: { crypto: 2000 },
    },
    liabilities: { credit_cards: { total: 16500 }, loans: {} },
    total_assets: 82400,
    total_liabilities: 16500,
    net_worth: 65900,
    created_at: "2025-12-01",
  },
  {
    id: "nw4",
    user_id: DEMO_USER_ID,
    snapshot_date: "2026-01-01",
    assets: {
      cash: { emergency_fund: 9500, checking: 12000 },
      retirement: { tesla_401k: 23000, roth_ira_his: 15600, roth_ira_hers: 12400 },
      investments: { schwab_brokerage: 6400, thinkorswim: 3800 },
      education: {},
      other: { crypto: 2100 },
    },
    liabilities: { credit_cards: { total: 15800 }, loans: {} },
    total_assets: 84800,
    total_liabilities: 15800,
    net_worth: 69000,
    created_at: "2026-01-01",
  },
  {
    id: "nw5",
    user_id: DEMO_USER_ID,
    snapshot_date: "2026-02-01",
    assets: {
      cash: { emergency_fund: 10000, checking: 12000 },
      retirement: { tesla_401k: 23000, roth_ira_his: 16000, roth_ira_hers: 12800 },
      investments: { schwab_brokerage: 6700, thinkorswim: 4000 },
      education: {},
      other: { crypto: 2200 },
    },
    liabilities: { credit_cards: { total: 15000 }, loans: {} },
    total_assets: 86700,
    total_liabilities: 15000,
    net_worth: 71700,
    created_at: "2026-02-01",
  },
  {
    id: "nw6",
    user_id: DEMO_USER_ID,
    snapshot_date: "2026-03-01",
    assets: {
      cash: { emergency_fund: 10000, checking: 12000 },
      retirement: { tesla_401k: 23000, roth_ira_his: 16400, roth_ira_hers: 13200 },
      investments: { schwab_brokerage: 7000, thinkorswim: 4200 },
      education: {},
      other: { crypto: 2300 },
    },
    liabilities: { credit_cards: { total: 15000 }, loans: {} },
    total_assets: 88100,
    total_liabilities: 15000,
    net_worth: 73100,
    created_at: "2026-03-01",
  },
];

export const demoBudgetCategories: BudgetCategory[] = [
  { id: "bc1", user_id: DEMO_USER_ID, name: "Rent", target_amount: 2700, category_group: "housing", created_at: "2026-01-01" },
  { id: "bc2", user_id: DEMO_USER_ID, name: "Groceries", target_amount: 800, category_group: "essentials", created_at: "2026-01-01" },
  { id: "bc3", user_id: DEMO_USER_ID, name: "Utilities", target_amount: 350, category_group: "essentials", created_at: "2026-01-01" },
  { id: "bc4", user_id: DEMO_USER_ID, name: "Transportation", target_amount: 600, category_group: "essentials", created_at: "2026-01-01" },
  { id: "bc5", user_id: DEMO_USER_ID, name: "Insurance (Auto/Renters)", target_amount: 250, category_group: "essentials", created_at: "2026-01-01" },
  { id: "bc6", user_id: DEMO_USER_ID, name: "Baby Supplies", target_amount: 600, category_group: "baby", created_at: "2026-01-01" },
  { id: "bc7", user_id: DEMO_USER_ID, name: "Debt Payoff", target_amount: 1800, category_group: "debt", created_at: "2026-01-01" },
  { id: "bc8", user_id: DEMO_USER_ID, name: "Emergency Fund", target_amount: 750, category_group: "savings", created_at: "2026-01-01" },
  { id: "bc9", user_id: DEMO_USER_ID, name: "Roth IRAs", target_amount: 1167, category_group: "investments", created_at: "2026-01-01" },
  { id: "bc10", user_id: DEMO_USER_ID, name: "Personal / Fun", target_amount: 500, category_group: "flex", created_at: "2026-01-01" },
  { id: "bc11", user_id: DEMO_USER_ID, name: "Subscriptions", target_amount: 150, category_group: "essentials", created_at: "2026-01-01" },
  { id: "bc12", user_id: DEMO_USER_ID, name: "Dining Out", target_amount: 300, category_group: "flex", created_at: "2026-01-01" },
];

export const demoExpenses: Expense[] = [
  { id: "e1", user_id: DEMO_USER_ID, category_id: "bc1", amount: 2700, description: "March Rent", date: "2026-03-01", is_baby_expense: false, baby_category: null, created_at: "2026-03-01" },
  { id: "e2", user_id: DEMO_USER_ID, category_id: "bc2", amount: 420, description: "Costco + Trader Joe's", date: "2026-03-05", is_baby_expense: false, baby_category: null, created_at: "2026-03-05" },
  { id: "e3", user_id: DEMO_USER_ID, category_id: "bc3", amount: 180, description: "SDG&E + Internet", date: "2026-03-03", is_baby_expense: false, baby_category: null, created_at: "2026-03-03" },
  { id: "e4", user_id: DEMO_USER_ID, category_id: "bc7", amount: 1800, description: "Debt payoff - March", date: "2026-03-01", is_baby_expense: false, baby_category: null, created_at: "2026-03-01" },
  { id: "e5", user_id: DEMO_USER_ID, category_id: "bc6", amount: 285, description: "Baby registry items", date: "2026-03-08", is_baby_expense: true, baby_category: "gear", created_at: "2026-03-08" },
  { id: "e6", user_id: DEMO_USER_ID, category_id: "bc4", amount: 95, description: "Gas", date: "2026-03-07", is_baby_expense: false, baby_category: null, created_at: "2026-03-07" },
  { id: "e7", user_id: DEMO_USER_ID, category_id: "bc12", amount: 85, description: "Date night", date: "2026-03-09", is_baby_expense: false, baby_category: null, created_at: "2026-03-09" },
  { id: "e8", user_id: DEMO_USER_ID, category_id: "bc10", amount: 45, description: "Books", date: "2026-03-10", is_baby_expense: false, baby_category: null, created_at: "2026-03-10" },
];

export const demoContacts: Contact[] = [
  { id: "c1", user_id: DEMO_USER_ID, role: "Estate Planning Attorney", section: "professional", name: null, organization: null, phone: null, email: null, notes: "Need to find — budget $2,000-2,500", sort_order: 1, created_at: "2026-01-01" },
  { id: "c2", user_id: DEMO_USER_ID, role: "Financial Advisor", section: "professional", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 2, created_at: "2026-01-01" },
  { id: "c3", user_id: DEMO_USER_ID, role: "CPA / Tax Preparer", section: "professional", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "c4", user_id: DEMO_USER_ID, role: "Insurance Agent (Life)", section: "professional", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 4, created_at: "2026-01-01" },
  { id: "c5", user_id: DEMO_USER_ID, role: "Insurance Agent (Auto/Home)", section: "professional", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 5, created_at: "2026-01-01" },
  { id: "c6", user_id: DEMO_USER_ID, role: "Employer HR (Tesla)", section: "professional", name: null, organization: "Tesla", phone: null, email: null, notes: null, sort_order: 6, created_at: "2026-01-01" },
  { id: "c7", user_id: DEMO_USER_ID, role: "Primary Care (Husband)", section: "medical", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 1, created_at: "2026-01-01" },
  { id: "c8", user_id: DEMO_USER_ID, role: "Primary Care (Wife)", section: "medical", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 2, created_at: "2026-01-01" },
  { id: "c9", user_id: DEMO_USER_ID, role: "OB/GYN", section: "medical", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "c10", user_id: DEMO_USER_ID, role: "Pediatrician", section: "medical", name: null, organization: null, phone: null, email: null, notes: "Need to select before baby arrives", sort_order: 4, created_at: "2026-01-01" },
  { id: "c11", user_id: DEMO_USER_ID, role: "Dentist", section: "medical", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 5, created_at: "2026-01-01" },
  { id: "c12", user_id: DEMO_USER_ID, role: "Pharmacy", section: "medical", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 6, created_at: "2026-01-01" },
  { id: "c13", user_id: DEMO_USER_ID, role: "Nearest Hospital/ER", section: "medical", name: null, organization: null, phone: null, email: null, notes: "Tri-City Medical Center, Vista", sort_order: 7, created_at: "2026-01-01" },
  { id: "c14", user_id: DEMO_USER_ID, role: "Guardian (Primary)", section: "emergency_family", name: null, organization: null, phone: null, email: null, notes: "MUST DISCUSS WITH WIFE", sort_order: 1, created_at: "2026-01-01" },
  { id: "c15", user_id: DEMO_USER_ID, role: "Guardian (Backup)", section: "emergency_family", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 2, created_at: "2026-01-01" },
  { id: "c16", user_id: DEMO_USER_ID, role: "Executor of Will", section: "emergency_family", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "c17", user_id: DEMO_USER_ID, role: "Successor Trustee", section: "emergency_family", name: null, organization: null, phone: null, email: null, notes: null, sort_order: 4, created_at: "2026-01-01" },
];

export const demoLegalDocuments: LegalDocument[] = [
  { id: "ld1", user_id: DEMO_USER_ID, doc_type: "Last Will — Husband", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld2", user_id: DEMO_USER_ID, doc_type: "Last Will — Wife", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld3", user_id: DEMO_USER_ID, doc_type: "Revocable Living Trust", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld4", user_id: DEMO_USER_ID, doc_type: "Financial POA — Husband", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld5", user_id: DEMO_USER_ID, doc_type: "Financial POA — Wife", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld6", user_id: DEMO_USER_ID, doc_type: "Healthcare Directive — Husband", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld7", user_id: DEMO_USER_ID, doc_type: "Healthcare Directive — Wife", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld8", user_id: DEMO_USER_ID, doc_type: "HIPAA Authorization — Husband", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld9", user_id: DEMO_USER_ID, doc_type: "HIPAA Authorization — Wife", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld10", user_id: DEMO_USER_ID, doc_type: "Marriage Certificate", status: "complete", storage_location: "Fireproof safe", file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld11", user_id: DEMO_USER_ID, doc_type: "Birth Certificate — Husband", status: "complete", storage_location: "Fireproof safe", file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld12", user_id: DEMO_USER_ID, doc_type: "Birth Certificate — Wife", status: "complete", storage_location: "Fireproof safe", file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld13", user_id: DEMO_USER_ID, doc_type: "Birth Certificate — Child", status: "not_started", storage_location: null, file_url: null, expiration_date: null, notes: "After birth — late 2026", created_at: "2026-01-01" },
  { id: "ld14", user_id: DEMO_USER_ID, doc_type: "Social Security Cards", status: "complete", storage_location: "Fireproof safe", file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ld15", user_id: DEMO_USER_ID, doc_type: "Passports", status: "complete", storage_location: "Fireproof safe", file_url: null, expiration_date: "2030-06-15", notes: null, created_at: "2026-01-01" },
  { id: "ld16", user_id: DEMO_USER_ID, doc_type: "Lease Agreement", status: "complete", storage_location: "Filing cabinet", file_url: null, expiration_date: null, notes: "Renting in Vista, CA", created_at: "2026-01-01" },
  { id: "ld17", user_id: DEMO_USER_ID, doc_type: "Vehicle Title(s)", status: "complete", storage_location: "Fireproof safe", file_url: null, expiration_date: null, notes: null, created_at: "2026-01-01" },
];

export const demoFinancialAccounts: FinancialAccount[] = [
  { id: "fa1", user_id: DEMO_USER_ID, institution: "Chase", account_type: "checking", last_four: "4521", owner: "Joint", beneficiary: null, login_reference: "See 1Password", approximate_balance: 12000, last_reviewed: "2026-03-01", notes: null, created_at: "2026-01-01" },
  { id: "fa2", user_id: DEMO_USER_ID, institution: "Ally Bank", account_type: "savings", last_four: "8834", owner: "Joint", beneficiary: null, login_reference: "See 1Password", approximate_balance: 10000, last_reviewed: "2026-03-01", notes: "Emergency fund", created_at: "2026-01-01" },
  { id: "fa3", user_id: DEMO_USER_ID, institution: "Fidelity (Tesla)", account_type: "retirement_401k", last_four: "2201", owner: "Husband", beneficiary: "Wife", login_reference: "See 1Password", approximate_balance: 23000, last_reviewed: "2026-02-15", notes: "Currently paused — resuming after debt payoff", created_at: "2026-01-01" },
  { id: "fa4", user_id: DEMO_USER_ID, institution: "Charles Schwab", account_type: "roth_ira", last_four: "7712", owner: "Husband", beneficiary: "Wife", login_reference: "See 1Password", approximate_balance: 16400, last_reviewed: "2026-03-01", notes: null, created_at: "2026-01-01" },
  { id: "fa5", user_id: DEMO_USER_ID, institution: "Charles Schwab", account_type: "roth_ira", last_four: "7718", owner: "Wife", beneficiary: "Husband", login_reference: "See 1Password", approximate_balance: 13200, last_reviewed: "2026-03-01", notes: null, created_at: "2026-01-01" },
  { id: "fa6", user_id: DEMO_USER_ID, institution: "Charles Schwab", account_type: "brokerage", last_four: "3301", owner: "Husband", beneficiary: null, login_reference: "See 1Password", approximate_balance: 7000, last_reviewed: "2026-03-01", notes: null, created_at: "2026-01-01" },
  { id: "fa7", user_id: DEMO_USER_ID, institution: "thinkorswim (Schwab)", account_type: "brokerage", last_four: "9904", owner: "Husband", beneficiary: null, login_reference: "See 1Password", approximate_balance: 4200, last_reviewed: "2026-03-01", notes: "Active trading account", created_at: "2026-01-01" },
];

export const demoInsurancePolicies: InsurancePolicy[] = [
  { id: "ip1", user_id: DEMO_USER_ID, policy_type: "Life Insurance — Tesla Employer", carrier: "MetLife", policy_number: null, coverage_amount: 150000, beneficiary: "Wife", monthly_premium: 0, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "2x salary, employer-paid. NOT portable if leaving Tesla.", created_at: "2026-01-01" },
  { id: "ip2", user_id: DEMO_USER_ID, policy_type: "Life Insurance — Supplemental (Husband)", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: null, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "NEED: ~$1.5-2M term policy. Get quotes from Ladder/Haven Life/Policygenius", created_at: "2026-01-01" },
  { id: "ip3", user_id: DEMO_USER_ID, policy_type: "Life Insurance — Wife", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: null, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "NEED: ~$500K-1M term policy", created_at: "2026-01-01" },
  { id: "ip4", user_id: DEMO_USER_ID, policy_type: "Disability — Short-term", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: 0, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "Tesla provided — verify details with HR", created_at: "2026-01-01" },
  { id: "ip5", user_id: DEMO_USER_ID, policy_type: "Disability — Long-term", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: 0, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "Tesla provided — verify details with HR", created_at: "2026-01-01" },
  { id: "ip6", user_id: DEMO_USER_ID, policy_type: "Health Insurance", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: null, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "Through Tesla", created_at: "2026-01-01" },
  { id: "ip7", user_id: DEMO_USER_ID, policy_type: "Auto Insurance", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: null, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ip8", user_id: DEMO_USER_ID, policy_type: "Renters Insurance", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: null, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: null, created_at: "2026-01-01" },
  { id: "ip9", user_id: DEMO_USER_ID, policy_type: "Umbrella Liability", carrier: null, policy_number: null, coverage_amount: null, beneficiary: null, monthly_premium: null, agent_name: null, agent_phone: null, agent_email: null, renewal_date: null, notes: "Consider after Phase 4 — $1M policy", created_at: "2026-01-01" },
];

export const demoMonthlyBills: MonthlyBill[] = [
  { id: "mb1", user_id: DEMO_USER_ID, name: "Rent", amount: 2700, due_date: 1, payment_method: "Chase Checking", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb2", user_id: DEMO_USER_ID, name: "SDG&E (Electric/Gas)", amount: 120, due_date: 15, payment_method: "Chase Checking", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb3", user_id: DEMO_USER_ID, name: "Internet (Cox)", amount: 80, due_date: 20, payment_method: "Chase Checking", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb4", user_id: DEMO_USER_ID, name: "Cell Phones", amount: 140, due_date: 12, payment_method: "Chase Checking", is_autopay: true, notes: "2 lines", created_at: "2026-01-01" },
  { id: "mb5", user_id: DEMO_USER_ID, name: "Car Insurance", amount: 180, due_date: 5, payment_method: "Chase Checking", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb6", user_id: DEMO_USER_ID, name: "Renters Insurance", amount: 25, due_date: 5, payment_method: "Chase Checking", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb7", user_id: DEMO_USER_ID, name: "Streaming (Netflix, Disney+, Spotify)", amount: 45, due_date: 10, payment_method: "Amazon Visa", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb8", user_id: DEMO_USER_ID, name: "Gym", amount: 50, due_date: 1, payment_method: "Citi Double Cash", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb9", user_id: DEMO_USER_ID, name: "iCloud+ / Apple One", amount: 20, due_date: 8, payment_method: "Amazon Visa", is_autopay: true, notes: null, created_at: "2026-01-01" },
  { id: "mb10", user_id: DEMO_USER_ID, name: "Adobe Creative Cloud", amount: 55, due_date: 18, payment_method: "Chase Sapphire", is_autopay: true, notes: "Photography business", created_at: "2026-01-01" },
];

export const demoDigitalAccess: DigitalAccess[] = [
  { id: "da1", user_id: DEMO_USER_ID, item_type: "password_manager", name: "1Password", details: "Master password location: sealed envelope in fireproof safe", status: "complete", created_at: "2026-01-01" },
  { id: "da2", user_id: DEMO_USER_ID, item_type: "password_manager", name: "Emergency Access", details: null, status: "not_setup", created_at: "2026-01-01" },
  { id: "da3", user_id: DEMO_USER_ID, item_type: "password_manager", name: "2FA Backup Codes", details: null, status: "not_setup", created_at: "2026-01-01" },
  { id: "da4", user_id: DEMO_USER_ID, item_type: "device", name: "iPhone", details: null, status: "not_setup", created_at: "2026-01-01" },
  { id: "da5", user_id: DEMO_USER_ID, item_type: "device", name: "MacBook Pro", details: null, status: "not_setup", created_at: "2026-01-01" },
  { id: "da6", user_id: DEMO_USER_ID, item_type: "device", name: "Work Computer (Tesla)", details: "Contact HR", status: null, created_at: "2026-01-01" },
  { id: "da7", user_id: DEMO_USER_ID, item_type: "account", name: "Primary Email (Gmail)", details: "See 1Password", status: null, created_at: "2026-01-01" },
  { id: "da8", user_id: DEMO_USER_ID, item_type: "account", name: "Apple ID / iCloud", details: "See 1Password", status: null, created_at: "2026-01-01" },
  { id: "da9", user_id: DEMO_USER_ID, item_type: "account", name: "Apple Developer Account", details: "See 1Password — has published apps", status: null, created_at: "2026-01-01" },
  { id: "da10", user_id: DEMO_USER_ID, item_type: "account", name: "GitHub", details: "See 1Password", status: null, created_at: "2026-01-01" },
  { id: "da11", user_id: DEMO_USER_ID, item_type: "legacy_setting", name: "Apple Legacy Contact", details: null, status: "not_setup", created_at: "2026-01-01" },
  { id: "da12", user_id: DEMO_USER_ID, item_type: "legacy_setting", name: "Google Inactive Account Manager", details: null, status: "not_setup", created_at: "2026-01-01" },
];

export const demoActionItems: ActionItem[] = [
  // Phase 1
  { id: "ai1", user_id: DEMO_USER_ID, title: "Get term life insurance quotes", description: "Ladder, Haven Life, Policygenius — target $1.5-2M for husband, $500K-1M for wife", phase: 1, status: "not_started", target_date: "2026-03-31", completed_date: null, notes: null, sort_order: 1, created_at: "2026-01-01" },
  { id: "ai2", user_id: DEMO_USER_ID, title: "Set up password manager", description: "1Password or Bitwarden — get all credentials migrated", phase: 1, status: "in_progress", target_date: "2026-03-15", completed_date: null, notes: "Using 1Password", sort_order: 2, created_at: "2026-01-01" },
  { id: "ai3", user_id: DEMO_USER_ID, title: "Share emergency access with wife", description: "1Password emergency kit + shared vault", phase: 1, status: "not_started", target_date: "2026-03-20", completed_date: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "ai4", user_id: DEMO_USER_ID, title: "Review ALL beneficiary designations", description: "401(k), Roth IRAs, investment accounts, bank accounts", phase: 1, status: "not_started", target_date: "2026-03-31", completed_date: null, notes: null, sort_order: 4, created_at: "2026-01-01" },
  { id: "ai5", user_id: DEMO_USER_ID, title: "Have guardian conversation with wife", description: "Decide primary + backup guardian for baby", phase: 1, status: "not_started", target_date: "2026-04-15", completed_date: null, notes: null, sort_order: 5, created_at: "2026-01-01" },
  { id: "ai6", user_id: DEMO_USER_ID, title: "Start filling in Emergency Binder", description: "Contacts, accounts, insurance policies, documents inventory", phase: 1, status: "in_progress", target_date: "2026-04-30", completed_date: null, notes: "Started digital version in FamilyVault", sort_order: 6, created_at: "2026-01-01" },
  // Phase 2
  { id: "ai7", user_id: DEMO_USER_ID, title: "Engage estate planning attorney", description: "Budget $2,000-2,500. Need will, trust, POA, healthcare directive", phase: 2, status: "not_started", target_date: "2026-05-15", completed_date: null, notes: null, sort_order: 1, created_at: "2026-01-01" },
  { id: "ai8", user_id: DEMO_USER_ID, title: "Complete will, trust, POA, healthcare directive", description: "Work with attorney to draft and execute all documents", phase: 2, status: "not_started", target_date: "2026-07-31", completed_date: null, notes: null, sort_order: 2, created_at: "2026-01-01" },
  { id: "ai9", user_id: DEMO_USER_ID, title: "Continue aggressive debt payoff", description: "$1,500-2,000/month toward credit cards (avalanche method)", phase: 2, status: "in_progress", target_date: "2026-12-31", completed_date: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "ai10", user_id: DEMO_USER_ID, title: "Add baby to health insurance within 30 days of birth", description: "Contact Tesla HR immediately after birth", phase: 2, status: "not_started", target_date: null, completed_date: null, notes: "Due late 2026", sort_order: 4, created_at: "2026-01-01" },
  { id: "ai11", user_id: DEMO_USER_ID, title: "Get baby's Social Security number", description: "Apply at hospital or SSA office", phase: 2, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 5, created_at: "2026-01-01" },
  { id: "ai12", user_id: DEMO_USER_ID, title: "Apply for baby's passport", description: "Both parents must be present with birth certificate", phase: 2, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 6, created_at: "2026-01-01" },
  // Phase 3
  { id: "ai13", user_id: DEMO_USER_ID, title: "Resume full Roth IRA contributions", description: "$7,000/yr each = $1,167/mo total", phase: 3, status: "not_started", target_date: null, completed_date: null, notes: "After debt is $0", sort_order: 1, created_at: "2026-01-01" },
  { id: "ai14", user_id: DEMO_USER_ID, title: "Re-enroll in Tesla 401(k)", description: "At minimum up to employer match", phase: 3, status: "not_started", target_date: null, completed_date: null, notes: "Currently paused", sort_order: 2, created_at: "2026-01-01" },
  { id: "ai15", user_id: DEMO_USER_ID, title: "Open California ScholarShare 529", description: "$200-300/mo on autopilot", phase: 3, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "ai16", user_id: DEMO_USER_ID, title: "Grow emergency fund to $60K", description: "$10K → $30K → $60K over 12-18 months", phase: 3, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 4, created_at: "2026-01-01" },
  { id: "ai17", user_id: DEMO_USER_ID, title: "Complete Emergency Binder", description: "All sections filled, documents scanned, letter of intent written", phase: 3, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 5, created_at: "2026-01-01" },
  { id: "ai18", user_id: DEMO_USER_ID, title: "Write Letter of Intent (first draft)", description: "Guardian wishes, asset instructions, personal messages", phase: 3, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 6, created_at: "2026-01-01" },
  // Phase 4
  { id: "ai19", user_id: DEMO_USER_ID, title: "Increase 401(k) to 15-20% of salary", description: "Beyond employer match", phase: 4, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 1, created_at: "2026-01-01" },
  { id: "ai20", user_id: DEMO_USER_ID, title: "Open house down payment HYSA", description: "Dedicated savings for eventual home purchase", phase: 4, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 2, created_at: "2026-01-01" },
  { id: "ai21", user_id: DEMO_USER_ID, title: "Build taxable brokerage beyond retirement", description: "Schwab individual brokerage", phase: 4, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 3, created_at: "2026-01-01" },
  { id: "ai22", user_id: DEMO_USER_ID, title: "Pursue Solutions Engineering career transition", description: "Target significant income increase", phase: 4, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 4, created_at: "2026-01-01" },
  { id: "ai23", user_id: DEMO_USER_ID, title: "Consider umbrella insurance policy", description: "$1M umbrella policy", phase: 4, status: "not_started", target_date: null, completed_date: null, notes: null, sort_order: 5, created_at: "2026-01-01" },
];
